name: Build LaTeX PDF
on:
  push:
    branches:
      - main
jobs:
  build_correctness_deciders:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile bbchallenge-paper.pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper.tex
          work_in_root_file_dir: true
      - name: Create branch with PDF file
        uses: EndBug/add-and-commit@v9
        with:
          add: '-f bbchallenge-paper.pdf'
          default_author: github_actions
          new_branch: build-paper-pdf
          push: 'origin build-paper-pdf --set-upstream --force'
